### ISSUE TITLE
Add Code of Conduct to website

### ISSUE THREAD

**Issue by alexanderlerch** [ismir2021/ismir2021.github.io#18]
This should be, at least for now, at the top level menu. The link to the google doc can be found in the diversity channel in slack.

**Comment by Ashvala** [comment]
I will have this done tomorrow!

**Comment by alexanderlerch** [comment]
Could you do that so that the direct link will be ismir2021.ismir.net/coc ?

**Comment by Ashvala** [comment]
Done! The permalink is, as requested, https://ismir2021.ismir.net/coc/
