### ISSUE TITLE
typo in paper title ('constrains')

### ISSUE THREAD

**Issue by alexanderlerch** [ismir2021/ismir2021.github.io#57]
https://github.com/ismir2021/ismir2021.github.io/blob/b670a445c2f582d6acc0b18a5f80008e1a59ad8b/_data/accepted.json#L2380

I didn't change it because I assume this is not the master file?

**Comment by Ashvala** [comment]
This is the file that is being used to render the accepted papers page. We can fix that typo up!

**Comment by alexanderlerch** [comment]
I was just concerned that this typo is also in the master paper list @ajaysmurthy

**Comment by ajaysmurthy** [comment]
Thanks for noticing - the typo has been fixed in CMT, master paper list and all subsequent places this info flows in.
