### ISSUE TITLE
Add Call for Tutorials

### ISSUE THREAD

**Issue by alexanderlerch** [ismir2021/ismir2021.github.io#7]
I attach the call for papers in markdown.

Action items:

- add this page (also to the menu - can we have a 'Calls' menu item?)
- add the relevant dates
- check if formatting is consistent with the Call for Papers page
[call_tutorials.zip](https://github.com/ismir2021/ismir2021.github.io/files/6002695/call_tutorials.zip)

Thanks!

**Comment by ashispati** [comment]
The email-id `ismir2021-tutorials@ismir.net` in the Call for Tutorials (appears in two places in the markdown file) does not have a hyperlink. Could you please edit the markdown to do so?

**Comment by Ashvala** [comment]
It should be fixed now!
